var Privacy = `<div data-custom-class="body">
<h3 class="c11" id="h.kgzcy9as12u5"><span class="c16 c10">1. INFORMATION COLLECTION</span></h3>
<p class="c4"><span class="c6">Users of the Service may be </span><span class="c6 c10">Clients</span><span class="c6">, </span><span class="c6 c10">Influencers</span><span class="c6">, or </span><span class="c6 c10">Agencies, or Site Visitors</span><span class="c6">&nbsp;(as each is defined in the </span><span class="c6">User Agreement</span><span class="c0">&nbsp;).</span></p>
<p class="c4"><span class="c27 c9 c10">Information You Provide to Us</span></p>
<p class="c4"><span class="c22 c9">When you use the Service, you may provide us with information about you. This may include your name and contact information, financial information to make or receive payment for services obtained through the Influenxing platform, or information to help us fill out tax forms. When you use the Service, we may also collect information related to your use of the Service and aggregate this with information about other users. This helps us improve our Services for you. You may also provide us with information about your contacts or friends if, for example, you&rsquo;d like to add those contacts to a message room. Agencies may also provide us with information about Influencers associated with the Agency.</span></p>
<ul class="c19 lst-kix_mom99jtp8wtw-0 start">
   <li class="c13 c15 li-bullet-0"><span class="c9 c10">Personal Information:</span><span class="c9">&nbsp;While using the Service (whether as a Cli</span><span class="c20">ent or Influencer or Agency), we ma</span><span class="c9">y require or otherwise collect information that identifies you as a specific individual and can be used to contact or identify you (&ldquo;</span><span class="c9 c10">Personal Information</span><span class="c1">&rdquo;). Examples of Personal Information include your name, email address, company address, billing address, and phone number.</span></li>
   <li class="c13 c15 li-bullet-0"><span class="c9 c10">Payment Information:</span><span class="c1">&nbsp;If you use the Service to make or receive payments, we will also collect certain payment information, such as credit card or other financial account information, and billing address.</span></li>
   <li class="c13 c15 li-bullet-0"><span class="c20 c10">Identity Verification:</span><span class="c25 c20 c38">&nbsp;We may collect Personal Information, such as your date of birth or taxpayer identification number, to validate your identity or as may be required by law, such as to complete tax filings. We may request documents to verify this information, such as a copy of your government-issued identification or photo or a billing statement.</span></li>
   <li class="c13 c15 li-bullet-0"><span class="c20 c10">Biometric Identifiers or Service Interaction Information: </span><span class="c25 c20 c38">We may collect Personal Information to verify your identity and to detect fraud, identity theft, or other misuse of your account through facial recognition and other technologies.This might be a photograph of your face, a selfie, or data about your interactions with the Service.We may request documents to verify this information, such as a copy of your government-issued ID. From time to time, Influenxing may require you to take and submit another or updated image of your face for comparison to your government-issued ID. The biometric identifiers or information collected are used only to verify your identity and platform security and use integrity purposes.</span></li>
   <li class="c13 c15 li-bullet-0"><span class="c20 c10">General Audience Service:</span><span class="c9">&nbsp;The Service is general audience and intended for users 18 and older. We do not knowingly collect Personal Information from anyone younger than age 18. If we become aware that a child younger than 18 has provided us with Personal Information, we will use commercially reasonable efforts to delete such information from our files. If you are the parent or legal guardian of a child younger than age 18 and believe that Influenxing has collected Personal Information from your child, please contact us at:</span><span class="c6">&nbsp;</span><span class="c28">legalnotices@Influenxing.com</span><span class="c31 c6">&nbsp;</span><span class="c1">.</span></li>
   <li class="c13 c15 li-bullet-0"><span class="c6 c10">Non-Identifying Information/Usernames:</span><span class="c9">&nbsp;We also may collect other information, such as zip codes, demographic data, information about your use of the Service, and general project-related data (&ldquo;</span><span class="c9 c10">Non-Identifying Information</span><span class="c9">&rdquo;). </span><span class="c17">We may combine information collected from Influenxing users, whether they are registered or not (&ldquo;</span><span class="c17 c10">Influenxing Users</span><span class="c17">&rdquo;). In some cases, we may render Personal Information (generally, email address) into a form of Non-Identifying Information referred to in this Privacy Policy as &ldquo;</span><span class="c6">&nbsp;</span><span class="c17 c10">Hashed Information</span><span class="c17">.&rdquo; This is typicall</span><span class="c1">y accomplished using a mathematical process (commonly known as a hash function) to convert information into a code. The code does not identify you directly, but it may be used to connect your activity and interests.</span></li>
   <li class="c13 c15 li-bullet-0"><span class="c9 c10">Combination of Personal and Non-Identifying Information:</span><span class="c1">&nbsp;Sometimes when non-identifying information is combined, it can identify an individual. For example, if a birthdate is combined with a first name, it might identify a person even if the birthday or first name alone could not. But the same pieces of information are considered Non-Identifying Information when they are taken alone or combined only with other non-identifying information (for example, your viewing preferences). We may combine your Personal Information with Non-Identifying Information, but Influenxing will treat the combined information as Personal Information.</span></li>
   <li class="c13 c15 li-bullet-0"><span class="c9 c10">Collection of Third Party Personal Information:</span><span class="c1">&nbsp;We collect the following personal information from you about your contacts or friends: First name, last name, and email address when you provide it to us for the purpose of adding your contacts to a message room.</span></li>
</ul>
<p class="c4"><span class="c1">You do not have a statutory obligation to provide us with any information, but you may have a contractual obligation to do so, and if we do not receive certain information from you, then we will not be able to provide our Service to you. If you have any questions regarding whether provision of information is mandatory and the consequences for withholding such information, please contact us using the contact information below.</span></p>
<p class="c4"><span class="c27 c9 c10">Information Received from Third Parties</span></p>
<p class="c4"><span class="c22 c9">Third parties may also give us information about you. If we combine that information with information about you collected through the Service, we will still treat that combined information as set forth in this Privacy Policy.</span></p>
<p class="c4"><span class="c1">We also may receive information about you from third parties. For example, we may supplement the information we collect with outside records or third parties may provide information in connection with a co-marketing agreement or at your request (such as if you choose to sign in with a third-party service). If we combine the information we receive from others with information we collect through the Service, we will treat the combined information as described in this Privacy Policy.</span></p>
<p class="c4"><span class="c27 c9 c10">Information Collected Automatically</span></p>
<p class="c4"><span class="c22 c9">Like other online companies, we receive technical information when you use our Services. We use these technologies to analyze how people use the Service, to improve how our Site functions, to save your log-in information for future sessions, and to serve you with advertisements that may interest you.</span></p>
<p class="c4"><span class="c1">We and our third party service providers, including analytics and third party content providers, may automatically collect certain information from you whenever you access or interact with the Service. This information may include, among other information, the browser and operating system you are using, the URL or advertisement that referred you to the Service, the search terms you entered into a search engine that led you to the Service, areas within the Service that you visited, which links you clicked on, which pages or content you viewed and for how long, other similar information and statistics about your interactions, such as content response times, download errors and length of visits to certain pages and other information commonly shared when browsers communicate with websites. We may combine this automatically collected log information with other information we collect about you. We do this to improve services we offer you, and to improve marketing, analytics, and site functionality.</span></p>
<p class="c4"><span class="c9">The information we collect also includes the Internet Protocol (&ldquo;</span><span class="c9 c10">IP</span><span class="c9">&rdquo;) address or other unique device identifier (&ldquo;</span><span class="c9 c10">Device Identifier</span><span class="c1">&rdquo;) for any device (computer, mobile phone, tablet, etc.) used to access the Service. A Device Identifier is a number that is automatically assigned or connected to the device you use to access the Service, and our servers identify your device by its Device Identifier. Some mobile service providers may also provide us or our third party service providers with information regarding the physical location of the device used to access the Service.</span></p>
<p class="c4"><span class="c27 c9 c10">Influenxing and its partners use cookies or similar technologies to analyze trends, administer the website, track users&rsquo; movement around the website, the desktop app, and the mobile app, and to gather demographic information about our user base as a whole. The technology used to collect information automatically from Influenxing Users may include the following:</span></p>
<ul class="c19 lst-kix_c4oln2oufvho-0 start">
   <li class="c13 c15 li-bullet-0"><span class="c9 c10">Cookies: </span><span class="c9">Like many websites, we and our marketing partners, affiliates, analytics, and service providers use &ldquo;cookies&rdquo; to collect information. A cookie is a small data file that we transfer to your computer&rsquo;s hard disk for record-keeping purposes. We use both persistent cookies that remain on your computer or similar device (such as to save your registration ID and login password for future logins to the Service and to track your compliance with the Influenxing Terms of Service) and session ID cookies, which expire at the end of your browser session (for example, to enable certain features of the Service, to better understand how Influenxing Users interact with the Service and to monitor aggregate usage by Influenxing Users and web traffic routing on the Service). You can control the use of cookies at the individual browser level, but if you choose to disable cookies, it may limit your use of certain features or functionality of the Service.</span><span class="c6">&nbsp;For further information on cookies and how they are used for the Service, please visit our Cookie Policy at </span><span class="c12"><a class="c8" href="https://www.google.com/url?q=https://www.influenxing.com/legal%23cookie-policy&amp;sa=D&amp;source=editors&amp;ust=1677516755912814&amp;usg=AOvVaw2hODDhZSM5YpD2hhUzPoLh">https://www.Influenxing.com/legal#cookie-policy</a></span><span class="c28 c32">.</span></li>
   <li class="c13 c15 li-bullet-0"><span class="c9 c10">Web Beacons: </span><span class="c1">We and our marketing partners, affiliates, analytics, and service providers may also employ software technology known as &ldquo;web beacons&rdquo; and/or &ldquo;tracking tags&rdquo; to help us keep track of what content on our Service is effective and to serve relevant advertising to you. Web beacons are small graphics with a unique identifier that may be invisible to you, and which are used to track the online activity of Internet users. Web beacons are embedded in the web pages you review or email messages you receive. Web beacons or similar technologies may be used for a number of purposes, including, without limitation, to count visitors to our Service, to monitor how Influenxing Users navigate the Service, to count how many emails that were sent were actually opened, or to count how many particular articles or links were actually viewed.</span></li>
   <li class="c13 c15 li-bullet-0"><span class="c9 c10">Embedded Scripts:</span><span class="c9">&nbsp;We and our marketing partners, affiliates, analytics, and service providers may also employ software technology known as an</span><span class="c6">&nbsp;</span><span class="c1">Embedded Script. An Embedded Script is programming code that is designed to collect information about your interactions with the Service, such as the links you click on. The code is temporarily downloaded onto your computer or other device and is deactivated or deleted when you disconnect from the Service.</span></li>
</ul>
<p class="c4"><span class="c1">In addition, we and our marketing partners, affiliates, analytics, and service providers may use a variety of other technologies (such as tags) that collect similar information for security and fraud detection purposes and we may use third parties to perform these services on our behalf.</span></p>
<p class="c4"><span class="c27 c9 c10">HOW WE RESPOND TO DO NOT TRACK SIGNALS</span></p>
<p class="c4"><span class="c9 c37">Influenxing</span><span class="c22 c9">&nbsp;does not respond to Do-Not-Track signals.</span></p>
<p class="c4"><span class="c9">Please note that your browser setting may allow you to automatically transmit a &ldquo;Do Not Track&rdquo; signal to websites and online services you visit. There is no consensus among industry participants as to what &ldquo;Do Not Track&rdquo; means in this context. Like many websites and online services, Influenxing does not alter its practices when it receives a &ldquo;Do Not Track&rdquo; signal from a visitor&rsquo;s browser. To find out more about &ldquo;Do Not Track,&rdquo; please visit </span><span class="c28"><a class="c8" href="https://www.google.com/url?q=http://www.allaboutdnt.com/&amp;sa=D&amp;source=editors&amp;ust=1677516755914374&amp;usg=AOvVaw3r1c-K846vJgLGGVSPnaJo">http://www.allaboutdnt.com</a></span><span class="c6">&nbsp;</span><span class="c1">.</span></p>
<p class="c4"><span class="c10 c18">The General Data Protection Regulation: Data Processing Agreement</span></p>
<p class="c4"><span class="c24">To streamline compliance with the General Data Protection Regulation (&ldquo;GDPR&rdquo;), Influenxing has posted a </span><span class="c31 c46"><a class="c8" href="https://www.google.com/url?q=https://influenxing.com/s/f89b37df-42d9-4971-bbcc-466469a68600/legal.html%23contract-hkc-19e1q&amp;sa=D&amp;source=editors&amp;ust=1677516755915211&amp;usg=AOvVaw3GjrnHXau3Ltm4riqUvmv_">Data Processing Agreement (&ldquo;DPA&rdquo;)</a></span><span class="c2">&nbsp;governing the relationship between the Customer (as defined in the DPA) acting as a data controller or processor, as applicable (and as defined in the DPA), of personal data under European Data Protection Legislation; and Influenxing (acting as a data processor or subprocessor, as applicable).</span></p>
<p class="c4"><span class="c24">Unless otherwise agreed to in writing by you and Influenxing, to the extent Influenxing processes any EU personal data for you as a controller (as defined by the General Data Protection Regulation (EU) 2016/679) in your role as a Customer, the </span><span class="c31 c24"><a class="c8" href="https://www.google.com/url?q=https://influenxing.com/s/f89b37df-42d9-4971-bbcc-466469a68600/legal.html%23contract-hkc-19e1q&amp;sa=D&amp;source=editors&amp;ust=1677516755915844&amp;usg=AOvVaw3UuGV3GR1Ve2dYjn3vvUj8">Data Processing Agreement</a></span><span class="c2">&nbsp;applies.</span></p>
<p class="c4"><span class="c27 c20 c10">Work Diaries and Work View</span></p>
<p class="c4"><span class="c22 c20">We collect information about a Influencer&rsquo;s work for a Client, including automatically collected information about work on a particular project. If a Influencer enables Work Diaries, we will share Work Diaries with the relevant Client and Agency. We tell Influencers when we are capturing information for the Work Diary and allow Influencers to block such data sharing.</span></p>
<p class="c4"><span class="c9">As part of the Service, when enabled by a Influencer, we collect information about a Influencer&rsquo;s work on a project for a Client. This feature is known as Work Diary. Work Diaries include information provided by the Influencer, such as a memo, as well as automatically gathered information about work on a project, such as number of mouseclicks and keyboard strokes and regularly taken screenshots (which may include a webcam picture of you if you have enabled this feature in your settings). In order to use Work Diaries, you must download and install the Team App software from </span><span class="c28"><a class="c8" href="https://www.google.com/url?q=http://www.influenxing.com/&amp;sa=D&amp;source=editors&amp;ust=1677516755916684&amp;usg=AOvVaw33cosK2hmjCbBiNEBGFvnS">www.Influenxing.com</a></span><span class="c6">&nbsp;</span><span class="c1">.</span></p>
<p class="c4"><span class="c1">We will share information contained in Work Diaries with the relevant Client and with any manager or administrator of any applicable Influencer Agency. We inform Influencers each time we capture information for Work Diary. As set forth in our Terms of Service, End User License Agreement, and help pages on the Site, a Influencer may choose to block or delete the screen shot and associated data for a recorded work interval, but then the Influencer may not be paid for that work interval. Influenxing may use de-identified or aggregated information from Work Diaries for statistical analysis, product development, marketing and research.</span></p>
<p class="c4"><span class="c27 c9 c10">User Profiles</span></p>
<p class="c4"><span class="c9 c37">Influencer</span><span class="c22 c9">s may create a profile, with certain or all information publicly available. Clients and Agencies may also create organization profiles.</span></p>
<p class="c4"><span class="c9">You may have the opportunity to create a profile, which consists of information about you, and may include Personal Information, photographs, examp les of your work, information on work previously performed via the Service and outside the Service, skills, tests taken, test scores, hourly pay rates and earnings information, feedback/rating information and other information, including your username (&ldquo;</span><span class="c9 c10">Profile</span><span class="c9">&rdquo;). The information in your Profile may be visible to all Influenxing Users and the general public subject to the privacy choices you make within your Influenxing Profile. If you choose to make your profile publicly visible, your profile will be visible to the entire Internet, including clients, Influencers, visitors, and search engines such as Google and Bing, and may appear on Influenxing partners&#39; sites. You may edit certain information in your Profile via your account and may choose to limit who is able to view certain content you post to your Profile. Clients and Agencies of associated individual users or companies may also have the opportunity to create an organization Profile. If, in any case, you believe that an unauthorized profile has been created about you, you can request for it to be removed by contacting us at </span><span class="c28"><a class="c8" href="https://www.google.com/url?q=https://support.influenxing.com/&amp;sa=D&amp;source=editors&amp;ust=1677516755917867&amp;usg=AOvVaw0yLD1glbfyEe4h_vV7Lyub">https://support.Influenxing.com</a></span><span class="c6">&nbsp;</span><span class="c1">or legalnotices@Influenxing.com.</span></p>
<p class="c4"><span class="c18 c10">Identity Verification</span></p>
<p class="c4"><span class="c18 c38">We place a premium on trust in our Service, so we may take steps to verify your identity.</span></p>
<p class="c4"><span class="c2">Before a Influencer can complete registration on the Service, or at any time thereafter, we may request or re-request identity verification. Without limiting the manner in which we request identity verification, we may require Influencers to participate in a video call after submitting their government issued ID to enable us to confirm that the Influencer is indeed the individual in the ID. We may record such video calls and take screenshots of the user during the call. Influenxing may use the information obtained from Identity Verification for purposes of verifying your identity, enforcing our Terms of Service and other agreements, and preventing fraud.</span></p>
<p class="c4"><span class="c27 c9 c10">Messaging</span></p>
<p class="c4"><span class="c9">Influencer</span><span class="c1">s, Agencies, and Clients may communicate with each other through the Service. For example, Influencers, Agencies, and Clients may wish to discuss Client needs and Influencer work proposals. If you communicate with an Agency or Client, that Agency or Client will also be a &ldquo;data controller&rdquo; with respect to such communications.</span></p>
<p class="c4"><span class="c27 c9 c10">Community Forums</span></p>
<p class="c4"><span class="c9 c22">We may offer public forums or blogs. If you participate, your comments and questions will be publicly displayed.</span></p>
<p class="c4"><span class="c9">The Service may provide you the opportunity to participate and post content publicly in forums, on blogs, through interactive features on Influenxing and through other communication functionality (&ldquo;</span><span class="c9 c10">Community Forums</span><span class="c9">&rdquo;). You may choose, through such features or otherwise, to submit or post questions, comments, or other content (collectively, &ldquo;</span><span class="c9 c10">User Forum Content</span><span class="c1">&rdquo;). Please note that certain information, such as your name and Profile may be publicly displayed on the Service along with your User Forum Content. Please note that your use of Community Forums is subject to the Influenxing Forum Rules and our Terms of Service.</span></p>
<p class="c4"><span class="c9 c10">Note that anything you post to a Community Forum is public </span><span class="c9 c10 c37">&mdash; </span><span class="c9 c10">others will have access to your User Forum Content and may use it or share it with third parties. If you choose to voluntarily disclose Personal Information in your User Forum Content or use Community Forums to link to your Profile, that information will be considered public information and the protections of this Privacy Policy will not apply</span><span class="c6">&nbsp;</span><span class="c1">.</span></p>
<p class="c4"><span class="c9 c37">To request removal of your personal information from our blog or community forum, contact us at </span><span class="c28 c37"><a class="c8" href="https://www.google.com/url?q=https://support.influenxing.com/&amp;sa=D&amp;source=editors&amp;ust=1677516755919622&amp;usg=AOvVaw11dMwPlAgg0rn5uV9c30Rf">https://support.Influenxing.com</a></span><span class="c6 c7">&nbsp;or legalnotices@Influenxing.com</span><span class="c6">&nbsp;</span><span class="c1">. In some cases, we may not be able to remove your Personal Information, in which case we will let you know if we are unable to do so and why.</span></p>
<p class="c4"><span class="c27 c9 c10">Testimonials</span></p>
<p class="c4"><span class="c9">We display personal testimonials of satisfied customers on our Service, in addition to other endorsements. With your consent we may post your testimonial along with your name. If you wish to update or delete your testimonial, you can contact us at </span><span class="c28"><a class="c8" href="https://www.google.com/url?q=https://support.influenxing.com/&amp;sa=D&amp;source=editors&amp;ust=1677516755920084&amp;usg=AOvVaw28flJGMPfOyS3u3_RK5aIp">https://support.Influenxing.com</a></span><span class="c43">&nbsp;or legalnotices@Influenxing.com</span><span class="c1">.</span></p>
<p class="c4"><span class="c27 c9 c10">Work Listings Through the Service</span></p>
<p class="c4"><span class="c1">If you choose to post a work listing via the Service as a Client, the contents of such listing will be viewable publicly, unless you designate the listing as only viewable through the Service or as private using the settings available on the applicable website. Work listings include information such as budget, location, history of work listing(s) by the Client, the names of other Influencers performing work for the Client, Client feedback and rating information and timing of project performance.</span></p>
<p class="c4"><span class="c27 c9 c10">Feedback</span></p>
<p class="c4"><span class="c9">We collect public and private feedback from Influenxing Users about their experience with other Influenxing Users of our Service. Please note that any public feedback that you provide via the Service about your experience with other Influenxing Users of our Service or that is provided about you by other Users is publicly viewable via the Service. On rare occasions, we may remove feedback pursuant to the relevant provisions of our Terms of Service, including the </span><span class="c12"><a class="c8" href="https://www.google.com/url?q=https://www.influenxing.com/legal%23terms-of-use&amp;sa=D&amp;source=editors&amp;ust=1677516755920773&amp;usg=AOvVaw1LA1uKl1u2x0gvaMP-OHxJ">Terms of Use</a></span><span class="c6 c31">&nbsp;</span><span class="c1">. Any private feedback that you provide via the Service about your experience with other Influenxing Users of our Service or that is provided about you by other Users will not be publicly viewable via the Service.</span></p>
<p class="c4"><span class="c1">We also collect feedback from Users about our Service. We use this information to respond to your inquiries, improve the Service and how our Site functions, and develop new products and features.</span></p>
<p class="c4"><span class="c9 c10 c27">Email to Friends and Referral Program</span></p>
<p class="c4"><span class="c9">Influenxing</span><span class="c1">&nbsp;lets you send project postings to friends via email. Influenxing also offers the ability to send friends emails about providing or purchasing services through the Service. You should only provide Influenxing contact information from individuals who are familiar to you and with their consent. If you choose to use either feature, your friend&rsquo;s email address will be used to send the requested posting and your email address will be used to copy you on the message to your friend or to send the message on your behalf. Influenxing stores this information for the sole purpose of sending this one-time email and tracking the success of our referral program.</span></p>
<p class="c4"><span class="c9">Your friend may contact us at </span><span class="c12"><a class="c8" href="https://www.google.com/url?q=https://support.influenxing.com/&amp;sa=D&amp;source=editors&amp;ust=1677516755921596&amp;usg=AOvVaw08rF7z1mI2wVwc6b2Sa6S_">https://support.Influenxing.com</a></span><span class="c1">&nbsp;or legalnotices@Influenxing.com to request that we remove this information from our database.</span></p>
<p class="c4"><span class="c27 c9 c10">Social Networking Services</span></p>
<p class="c4"><span class="c22 c9">You may register for an account directly with our Site, or through a social networking service. If you register with a social networking service (or later link your account to one), we will collect certain information about you from that social networking service, and what we collect depends on your privacy settings with that social networking service. The Service may also allow you to &ldquo;like&rdquo; or share content with social networking services.</span></p>
<p class="c4"><span class="c9">You may register to join the Service directly via the Service or by logging into your account with a third party social networking service (&ldquo;</span><span class="c9 c10">SNS</span><span class="c1">&rdquo;) via our Service (e.g., Facebook, Github and other third party services that let you sign in using your existing credentials with those services). If you choose to register via an SNS, or to later link your account with the Service to your account with an SNS, we will use the Personal Information you have provided to the SNS (such as your name, email address, gender and other information you make publicly available via the SNS) to create your account. Note that the information we collect from and through an SNS may depend on the privacy settings you have set with the SNS and the permissions you grant to us in connection with linking your account with the Service to your account with an SNS. Other than what we may share with the SNS as described below, the Personal Information an SNS has about you is obtained by the SNS independent of our Service, and Influenxing is not responsible for it.</span></p>
<p class="c4"><span class="c1">The Influenxing Service also may permit additional interactions between it and a third party website, service, or other content provider, such as enabling you to &ldquo;like&rdquo; or share content to a third party SNS. If you choose to &ldquo;like&rdquo; or share content, or to otherwise share information from or via our Service with a third party site or service, that information may be publicly displayed, and the third party may have access to information about you and your use of our Service (and we may have access to information about you from that third party). These features may collect your IP address, which page you are visiting on our site, and may set a cookie to enable the feature to function properly. Your interactions with third parties through an SNS or similar features are governed by the respective privacy policies of those third parties.</span></p>
<p class="c4"><span class="c1">You represent that you are entitled to use your SNS account for the purposes described herein without breach by you of any of the terms and conditions that govern the SNS, and without obligating Influenxing to pay any fees or making Influenxing subject to any usage limitations imposed by such SNS. You can disable the link between your Influenxing account and your SNS account at any time through the &ldquo;Settings&rdquo; section of our Service. Please note that your relationship with any SNS is governed solely by your agreement(s) with such SNS. If your SNS account terminates, then functions enabled through the link between your Influenxing account and your SNS account will terminate as well.</span></p>
<p class="c4"><span class="c27 c9 c10">SMS Terms of Service</span></p>
<p class="c4"><span class="c0">US Short Code Terms of Service</span></p>
<p class="c4"><span class="c0">Influenxing Alerts</span></p>
<ul class="c19 lst-kix_oi3ikoonc4n-0 start">
   <li class="c13 c15 li-bullet-0"><span class="c0">For users who opt-in, the Influenxing Alerts SMS program sends helpful reminders related to activity on the Influenxing platform and other marketing and promotional messages such as event invitations and job posting support.</span></li>
   <li class="c13 c15 li-bullet-0"><span class="c0">Users may opt-in to the program by texting &ldquo;JOIN&rdquo; to Influenxing. The number of messages received may vary based on user activity. Messaging and data usage rates may apply to all text messages between you and Influenxing. If you have any questions about your text plan or data plan, it is best to contact your wireless provider. This program is provided as a service to you, and neither Influenxing nor your mobile carrier will be responsible or liable for delayed or undelivered messages.</span></li>
   <li class="c13 c15 li-bullet-0"><span class="c0">You can cancel the SMS service at any time by texting &quot;STOP&quot; to Influenxing. After you send the SMS message &quot;STOP&quot; to us, you will receive an SMS message confirming that you have been unsubscribed and you should no longer receive marketing SMS messages from us. To opt-in again, just sign up as you did the first time and we will start sending SMS messages to you again.</span></li>
   <li class="c13 c15 li-bullet-0"><span class="c0">If you are experiencing issues with the messaging program, you can reply with the keyword &ldquo;HELP&rdquo; for more assistance, or you can get help directly at support.Influenxing.com.</span></li>
</ul>
<h3 class="c11" id="h.j5x39ldxvo2y"><span class="c16 c10">2. USE OF INFORMATION</span></h3>
<p class="c4"><span class="c22 c9">We use information collected through the Service to provide and improve the Service, process your requests, prevent fraud, provide you with information and advertising that may interest you, comply with the law, and as otherwise permitted with your consent.</span></p>
<p class="c4"><span class="c27 c9 c10">WE USE INFORMATION WE COLLECT:</span></p>
<ul class="c19 lst-kix_omtz1kof1g2c-0 start">
   <li class="c13 c15 li-bullet-0"><span class="c1">To provide and improve the Service, complete your transactions, address your inquiries, process your registration, verify the information you provide is valid, and for compliance and internal business purposes.</span></li>
   <li class="c13 c15 li-bullet-0"><span class="c9">To contact you with administrative communications and Influenxing newsletters, marketing or promotional materials (on behalf of Influenxing or third parties) and other information that may be of interest to you. If you decide at any time that you no longer wish to receive such communications from us, please follow the instructions in the </span><span class="c31 c40"><a class="c8" href="https://www.google.com/url?q=https://www.influenxing.com/legal%23YourChoices&amp;sa=D&amp;source=editors&amp;ust=1677516755924102&amp;usg=AOvVaw3gQvxbQ-fGb6Lwlpus2-NU">Your Choices and Rights</a></span><span class="c6">&nbsp;</span><span class="c1">section, below.</span></li>
   <li class="c13 c15 li-bullet-0"><span class="c1">To tailor content we display to you and offers we may present to you, both on the Service and elsewhere online.</span></li>
   <li class="c13 c15 li-bullet-0"><span class="c1">To administer and develop our business relationship with you and, if applicable, the corporation or other legal entity you represent.</span></li>
   <li class="c13 c15 li-bullet-0"><span class="c1">To assess your proposal to perform a freelance project for Influenxing and prepare related governmental and internal statistics reports.</span></li>
   <li class="c13 c15 li-bullet-0"><span class="c1">To enforce and comply with the law, including to conduct an investigation, to protect the property and rights of Influenxing or a third party, to protect the safety of the public or any person, or to prevent or stop activity we may consider to be, or to pose a risk of being, illegal, fraudulent, unethical or legally actionable activity. We may also use Device Identifiers to identify Influenxing Users.</span></li>
   <li class="c13 c15 li-bullet-0"><span class="c1">For the purposes disclosed at the time you provide your information, with your consent, and as further described in this Privacy Policy.</span></li>
</ul>
<p class="c4"><span class="c1">We use your Personal Information for the purposes described above:</span></p>
<ul class="c19 lst-kix_uy0y2aey9q1v-0 start">
   <li class="c13 c15 li-bullet-0"><span class="c1">To Honor Our Contractual Commitments to You. Much of our processing of Personal Information is to meet our contractual obligations to our investors, or to take steps at Users&#39; request in anticipation of entering into a contract with them.</span></li>
   <li class="c13 c15 li-bullet-0"><span class="c1">For Our Legitimate Interests. In many cases, we handle Personal Information on the grounds that it furthers our legitimate interests in commercial activities, such as the following, in ways that are not overridden by the interests or fundamental rights and freedoms of the affected individuals:</span></li>
</ul>
<ul class="c19 lst-kix_uy0y2aey9q1v-1 start">
   <li class="c3 li-bullet-0"><span class="c25 c42 c38">Providing our Site and Service.</span></li>
   <li class="c3 li-bullet-0"><span class="c2">Detecting security incidents, protecting against malicious, deceptive, fraudulent or illegal activity, and prosecuting those responsible for that activity.</span></li>
   <li class="c3 li-bullet-0"><span class="c2">Measuring interest and engagement in our Services.</span></li>
   <li class="c3 li-bullet-0"><span class="c2">Short-term, transient use, such as contextual customization of ads.</span></li>
   <li class="c3 li-bullet-0"><span class="c2">Improving, upgrading or enhancing our Services.</span></li>
   <li class="c3 li-bullet-0"><span class="c2">Developing new products and services.</span></li>
   <li class="c3 li-bullet-0"><span class="c2">Ensuring internal quality control and safety.</span></li>
   <li class="c3 li-bullet-0"><span class="c2">Authenticating and verifying individual identities.</span></li>
   <li class="c3 li-bullet-0"><span class="c2">Debugging to identify and repair errors with our Services.</span></li>
   <li class="c3 li-bullet-0"><span class="c2">Auditing relating to interactions, transactions and other compliance activities.</span></li>
   <li class="c3 li-bullet-0"><span class="c2">Enforcing our agreements and policies.</span></li>
   <li class="c3 li-bullet-0"><span class="c2">Analyzing and improving our business.</span></li>
   <li class="c3 li-bullet-0"><span class="c2">Communications, including marketing and responding to your inquiries about our services.</span></li>
   <li class="c3 li-bullet-0"><span class="c25 c38 c42">Addressing information security needs and protecting our Users, Influenxing, and others.</span></li>
   <li class="c3 li-bullet-0"><span class="c25 c42 c38">Managing legal issues.</span></li>
</ul>
<ul class="c19 lst-kix_uy0y2aey9q1v-0">
   <li class="c13 c15 li-bullet-0"><span class="c1">To Comply with Legal Obligations. We need to use and disclose Personal Information in certain ways to comply with our legal obligations.</span></li>
</ul>
<h3 class="c11" id="h.39zrplhrdbr2"><span class="c16 c10">3. DATA RETENTION</span></h3>
<p class="c4"><span class="c9">Unless you request that we delete certain information (see </span><span class="c31 c40"><a class="c8" href="https://www.google.com/url?q=https://www.influenxing.com/legal%23YourChoices&amp;sa=D&amp;source=editors&amp;ust=1677516755926412&amp;usg=AOvVaw30ZlbMogqIDC8sWlu6lZbs">Your Choices and Rights </a></span><span class="c9">below), </span><span class="c20">we retain government-issued identification documents you submit to verify your identity for 40 days, selfies you submit to verify your identity for 180 days, a copy of the headshot image from your identity document for 5 years, and other information w</span><span class="c1">e collect for at least 5 years. Your information may persist in copies made for backup and business continuity purposes for additional time. If you choose to provide us with Personal Information, we encourage you to routinely update the data to ensure that we have accurate and up-to-date information about you.</span></p>
<h3 class="c11" id="h.90nszemkt9mc"><span class="c16 c10">4. INFORMATION SHARING AND DISCLOSURE</span></h3>
<p class="c4"><span class="c22 c9">We may share information about you to provide the Services, for legal and investigative purposes, in connection with sweepstakes and promotions, or if we are part of a merger or acquisition. We may also share non-identifying information with third parties. You have choices as to whether we share your personal information with third parties for their own marketing purposes.</span></p>
<p class="c4"><span class="c1">We may share aggregated Non-Identifying Information and we may otherwise disclose Non-Identifying Information (including, without limitation, Hashed Information) to third parties. We do not share your Personal Information with third parties for those third parties&rsquo; marketing purposes unless we first provide you with the opportunity to opt-in to or opt-out of such sharing. We may also share the information we have collected about you, including Personal Information, as disclosed at the time you provide your information, with your consent, as otherwise described in this Privacy Policy, or in the following circumstances:</span></p>
<ul class="c19 lst-kix_n12qka1n9jh-0 start">
   <li class="c13 c15 li-bullet-0"><span class="c9 c10">Information about Influencers Shared with Clients, Agencies, Influenxing Payroll Vendors, and Partners of The Influenxing Foundation Initiative: </span><span class="c1">We share information regarding Influencers who have entered into a contract with a Client or who have elected to participate in Influenxing Payroll, including information in Work Diaries and work history, with Clients, Agencies and Influenxing Payroll vendors. Note that if a Influencer is suspended from the Influenxing Service, we may share that information with Clients for whom that Influencer has worked or submitted proposals for work. We may also share information with Agencies to whom Influencers are associated for a particular work project. If you choose to view a job post or submit a proposal for work as a Influencer via the Service, we may share relevant information with the applicable Client(s), including, but not limited to, the information contained in your Influencer Profile. If you choose to participate in The Influenxing Foundation Initiative as a Influencer, we may share information relevant to your participation in the program with partners of Influenxing who provide support to Influencers through that program.</span></li>
   <li class="c13 c15 li-bullet-0"><span class="c9 c10">Information about Clients and Agencies Shared with Influencers: </span><span class="c1">If you have entered into a service contract or agreed to use Influenxing Payroll with another user, we may provide him/her with your name, company address, billing address, or tax ID or VAT number in order to complete the transaction or to facilitate the resolution of a claim or dispute. The user receiving your information is not allowed to use it for purposes unrelated to the transaction, such as to contact you for marketing purposes, unless you have expressly consented to it.</span></li>
   <li class="c13 c15 li-bullet-0"><span class="c9 c10">Service Providers: </span><span class="c1">We may employ third party companies and individuals to facilitate our Service, to provide the Service on our behalf, to perform Service-related services (e.g., without limitation, maintenance services, database management, web analytics and online advertising, payment processing, fraud detection and improvement of Influenxing&rsquo;s features) or to assist us in analyzing how our Service is used. These third parties may have access to your Personal Information in order to perform these tasks on our behalf.</span></li>
   <li class="c13 c15 li-bullet-0"><span class="c9 c10">What Happens If You Agree to Receive Information from Third Parties or Request that We Share Your Information:</span><span class="c1">&nbsp;You may be presented with an opportunity to receive information and/or marketing offers from one or more third parties. If you agree at that time to have your Personal Information shared, your Personal Information will be disclosed to that third party (or parties) and will be subject to the privacy policy and practices of that third party. We are not responsible for the privacy policies and practices of third parties, and, if you later decide that you no longer want to receive communications from a third party, you will need to contact that third party directly. You also may request, sometimes through your use of an SNS or similar interactive feature or third party application, that we share information about you with a third party and we will typically do so under those circumstances.</span></li>
   <li class="c13 c15 li-bullet-0"><span class="c24 c10">Legal and Investigative Purposes: </span><span class="c24">Influenxing</span><span class="c2">&nbsp;will share information with government agencies as required by law in response to lawful requests by public authorities, including to meet national security or law enforcement requirements and, including without limitation, in connection with reporting earnings. We cooperate with government and law enforcement officials and private parties to enforce and comply with the law. We will disclose information about you to government or law enforcement officials or private parties as we, in our sole discretion, believe necessary or appropriate to respond to claims and legal process (including but not limited to subpoenas), or, at the request of governmental authorities or other third parties conducting an investigation where we determine in our sole discretion the disclosure is necessary to (a) protect the property and rights of Influenxing or a third party, (b) protect the safety of the public or any person, or (c) prevent or stop activity we may consider to be, or pose a risk of being, illegal, fraudulent, unethical or legally actionable activity.</span></li>
   <li class="c13 c15 li-bullet-0"><span class="c9 c10">Internal and Business Transfers: </span><span class="c9">Influenxing</span><span class="c1">&nbsp;may share information, including Personal Information, with its parent company Influenxing Inc., and any current or future subsidiaries or affiliates, primarily for business and operational purposes, including activities such as IT management, for them to provide services to you, or support and supplement the Services we provide. We may sell, transfer, or otherwise share some or all of our assets, including your Personal Information, in connection with a merger, acquisition, reorganization or sale of assets (including, in each case, as part of the due-diligence process with any potential acquiring entity) or in the event of bankruptcy.</span></li>
   <li class="c13 c15 li-bullet-0"><span class="c9 c10">Sweepstakes, Contests, and Promotions:</span><span class="c9">&nbsp;We may offer sweepstakes, contests, and other promotions (any, a &ldquo;</span><span class="c9 c10">Promotion</span><span class="c1">&rdquo;) that may require registration. By participating in a Promotion, you are agreeing to the official rules that govern that Promotion, which may contain specific requirements of you, including, except where prohibited by law, allowing the sponsor(s) of the Promotion to use your name, voice, likeness, or other indicia of persona in advertising or marketing associated with the Promotion. If you choose to enter a Promotion, your Personal Information may be disclosed to third parties or the public in connection with the administration of such Promotion, including, without limitation, in connection with winner selection, prize fulfillment, and as required by law or permitted by the Promotion&rsquo;s official rules, such as on a winner&rsquo;s list.</span></li>
</ul>
<h3 class="c11" id="h.yj0njesj2n8o"><span class="c16 c10">5. THIRD PARTY ANALYTICS PROVIDERS, AD SERVERS AND SIMILAR THIRD PARTIES</span></h3>
<p class="c4"><span class="c22 c9">We may work with advertising agencies and vendors who use technology to help us understand how people use our Site. These vendors may use technologies to serve you advertisements that may interest you. You can choose to opt out of receiving interest-based advertising.</span></p>
<p class="c4"><span class="c9">Influenxing</span><span class="c9">&nbsp;works with (or may in the future work with) network advertisers, ad agencies, analytics service providers and other vendors to provide us with information regarding traffic on the Service, including pages viewed and the actions taken when visiting the Service; to serve our advertisements on other websites, within mobile apps and elsewhere online; and to provide us with information regarding the use of the Service and the effectiveness of our advertisements. Our service providers may collect certain information about your visits to and activity on the Service as well as other websites or services, they may set and access their own tracking technologies on your device (including </span><span class="c28"><a class="c8" href="https://www.google.com/url?q=https://www.influenxing.com/legal%23cookies&amp;sa=D&amp;source=editors&amp;ust=1677516755928973&amp;usg=AOvVaw0SiUqKSk2EKCkLHwQZ9689">cookies</a></span><span class="c6">&nbsp;</span><span class="c9">and </span><span class="c28"><a class="c8" href="https://www.google.com/url?q=https://www.influenxing.com/legal%23webbeacons&amp;sa=D&amp;source=editors&amp;ust=1677516755929303&amp;usg=AOvVaw060JHjFqRcchIGk-2zYPU4">web beacons</a></span><span class="c6">&nbsp;</span><span class="c9">), and may use that information to show you targeted advertisements. Some of these parties may collect Personal Information when you visit the Service or other online websites and services. We may also share certain Non-Identifying Information with these parties, including Hashed Information, in connection with the services they provide to us. If you wish to opt out of interest-based advertising, click </span><span class="c12"><a class="c8" href="https://www.google.com/url?q=http://optout.aboutads.info/&amp;sa=D&amp;source=editors&amp;ust=1677516755929589&amp;usg=AOvVaw0HtKaTeii3lzj_He0wK_fx">here</a></span><span class="c6">&nbsp;</span><span class="c9">(or if located in the European Union, click</span><span class="c6">&nbsp;</span><span class="c28"><a class="c8" href="https://www.google.com/url?q=http://www.youronlinechoices.eu/&amp;sa=D&amp;source=editors&amp;ust=1677516755929836&amp;usg=AOvVaw0Q0huq7Tc-b1Dn7ZBPhkqI">here</a></span><span class="c6">&nbsp;</span><span class="c1">). If you choose to opt out, please note you will continue to receive generic ads.</span></p>
<p class="c4"><span class="c9">While we may use a variety of service providers to perform advertising services, some of these companies are members of the Network Advertising Initiative (&ldquo;</span><span class="c9 c10">NAI</span><span class="c9">&rdquo;) or the Digital Advertising Alliance (&ldquo;</span><span class="c9 c10">DAA</span><span class="c9">&rdquo;) Self-Regulatory Program for Online Behavioral Advertising. You may want to visit </span><span class="c28"><a class="c8" href="https://www.google.com/url?q=http://www.networkadvertising.org/managing/opt_out.asp&amp;sa=D&amp;source=editors&amp;ust=1677516755930298&amp;usg=AOvVaw1XX-uaZuODaVJjd2edkRTn">http://www.networkadvertising.org/managing/opt_out.asp</a></span><span class="c6">&nbsp;</span><span class="c9">, which provides information regarding targeted advertising and the &ldquo;opt-out&rdquo; procedures of NAI members. You may also want to visit </span><span class="c28"><a class="c8" href="https://www.google.com/url?q=http://www.aboutads.info/choices/&amp;sa=D&amp;source=editors&amp;ust=1677516755930586&amp;usg=AOvVaw1N3LGG84fQlkGKyCfd9bE6">http://www.aboutads.info/choices/</a></span><span class="c6">&nbsp;</span><span class="c1">, which provides information regarding targeted advertising and offers an &ldquo;opt-out&rdquo; by participating companies in the DAA Self-Regulatory Program.</span></p>
<h3 class="c11" id="h.n5wpxb87t47x"><span class="c16 c10">6. YOUR CHOICES AND RIGHTS</span></h3>
<p class="c4"><span class="c22 c9">According to applicable law, you may have certain choices and rights associated with your personal information.</span></p>
<p class="c4"><span class="c5">Communication Preferences.</span></p>
<ul class="c19 lst-kix_e82r2e20etxo-0 start">
   <li class="c13 c15 li-bullet-0"><span class="c1">Registered Influenxing Users may update their choices regarding the types of communications you receive from us through your online account.</span></li>
   <li class="c13 c15 li-bullet-0"><span class="c1">You may opt-out of receiving marketing emails from us by following the opt-out instructions provided in those emails. Please note that we reserve the right to send you certain communications relating to your account or use of the Service (for example, administrative and service announcements) via email and other means and these transactional account messages may be unaffected if you opt-out from receiving marketing communications.</span></li>
   <li class="c13 c15 li-bullet-0"><span class="c1">You may opt-out of receiving text messages by replying &ldquo;STOP&rdquo; to any text message received.</span></li>
   <li class="c13 c15 li-bullet-0"><span class="c1">Registered Influenxing Users who access the Service by using an Influenxing mobile application may, with permission, receive push notifications. Similarly, registered Influenxing Users who access the Service by using certain desktop browsers may, with permission, receive push notifications. Notification preferences can be modified in the settings menu for the mobile application or the applicable browser.</span></li>
</ul>
<p class="c4"><span class="c9 c10 c25">Data Subject Rights.</span></p>
<p class="c4"><span class="c1">In accordance with applicable law, you may have the right to:</span></p>
<ul class="c19 lst-kix_l2m2qba5tzi6-0 start">
   <li class="c13 c15 li-bullet-0"><span class="c9 c10">Access Personal Information </span><span class="c1">about you, including: (i) confirming whether we are processing your personal information; (ii) obtaining access to or a copy of your personal information.</span></li>
   <li class="c13 c15 li-bullet-0"><span class="c9 c10">Request Correction </span><span class="c1">of your personal information where it is inaccurate, incomplete or outdated. In some cases, you can update your personal information within your Influenxing account by logging in and visiting settings/user settings.</span></li>
   <li class="c13 c15 li-bullet-0"><span class="c9 c10">Request Deletion, Anonymization or Blocking</span><span class="c1">&nbsp;of your personal information when processing is based on your consent or when processing is unnecessary, excessive or noncompliant. Note that if your information is deleted, then your account may become deactivated. If your account is deactivated or you ask to close your account, you will no longer be able to use the Service. If you would like to close your account in our system, you can do so through the Influenxing Service (once you have logged in, visit settings / user settings, and then click on the close my account link).</span></li>
   <li class="c13 c15 li-bullet-0"><span class="c9 c10">Request Restriction of or Object to</span><span class="c1">&nbsp;our processing of your personal information when processing is noncompliant.</span></li>
   <li class="c13 c15 li-bullet-0"><span class="c9 c10">Withdraw your Consent </span><span class="c1">to our processing of your personal information. If you refrain from providing personal information or withdraw your consent to processing, some features of our Service may not be available.</span></li>
   <li class="c13 c15 li-bullet-0"><span class="c9 c10">Request data portability</span><span class="c1">&nbsp;and receive an electronic copy of personal information that you have provided to us.</span></li>
   <li class="c13 c15 li-bullet-0"><span class="c9 c10">Be informed</span><span class="c1">&nbsp;about third parties with which your personal information has been shared.</span></li>
   <li class="c13 c15 li-bullet-0"><span class="c9 c10">Request the review of decisions</span><span class="c1">&nbsp;taken exclusively based on automated processing if that could affect data subject rights.</span></li>
</ul>
<p class="c4"><span class="c9">P</span><span class="c20">lease see our</span><span class="c29"><a class="c8" href="https://www.google.com/url?q=https://www.influenxing.com/legal%23gdpr&amp;sa=D&amp;source=editors&amp;ust=1677516755933239&amp;usg=AOvVaw1GHgjfVtLQF-bEMKDGUNzG">&nbsp;Privacy Center</a></span><span class="c20">&nbsp;for more information or to submit a request to us regarding your Personal Information. Influenxing uses automated means to calculate the Job Success Score of Influencers. If you believe that our services have miscalculated your Job Success Score or you would like to exercise any other rights with regard to your Personal Information</span><span class="c9">, please email us at </span><span class="c31 c36">privacyrequests@Influenxing.com</span><span class="c1">&nbsp;for assistance. We may be able to assist you by conducting a manual review of your Job Success Score, such as by assessing whether the information you&rsquo;ve provided us is accurate. While we strongly encourage you to first raise any questions or concerns about your Personal Information directly with us, you have a right to lodge a complaint with the relevant supervisory authority and to seek judicial remedy.</span></p>
<p class="c4"><span class="c9">We will use commercially reasonable efforts to honor your requests for deletion; however, certain information will actively persist on the Service even if you close your account, including information in your Work Diaries and messages you posted to the </span><span class="c20">Service</span><span class="c9">. </span><span class="c49">In addition, the rights described above may be limited, for example, if fulfilling your request would reveal personal information about another person, or if you ask us to delete information we are required by law to keep or have compelling legitimate interests in keeping (such as for fraud prevention purposes). Y</span><span class="c1">our Personal Information may remain in our archives and information you update or delete, or information within a closed account, may persist internally for our administrative purposes, to the extent permitted by law. In addition, we typically will not remove information you posted publicly through or on the Service. Bear in mind that neither you nor Influenxing can delete all copies of information that has been previously shared with others on the Service.</span></p>
<h3 class="c11" id="h.sgz8zgrlljy2"><span class="c16 c10">7. SECURITY</span></h3>
<p class="c4"><span class="c22 c20">We take a number of steps to protect your data, but no security is guaranteed.</span></p>
<p class="c4"><span class="c9">Influenxing</span><span class="c9">&nbsp;takes commercially reasonable steps to help protect and secure the information it collects and stores about Influenxing Users. All access to the Site is encrypted using industry-standard transport layer security technology (&ldquo;</span><span class="c9 c10">TLS</span><span class="c9">&rdquo;). When you enter sensitive information (such as tax identification number), we encrypt the transmission of that information using secure socket layer technology (&ldquo;</span><span class="c9 c10">SSL</span><span class="c1">&rdquo;). We also use HTTP strict transport security to add an additional layer of protection for our Influenxing Users. But remember that no method of transmission over the Internet, or method of electronic storage, is 100% secure. Thus, while we strive to protect your Personal Information, Influenxing cannot ensure and does not warrant the security of any information you transmit to us.</span></p>
<h3 class="c11" id="h.rw8yni2a590x"><span class="c16 c10">8. INTERNATIONAL TRANSFER OF PERSONAL INFORMATION</span></h3>
<p class="c4"><span class="c22 c9">Because we are a Indian company, we process and store your information in the India and our service providers may process and store it elsewhere.</span></p>
<p class="c4"><span class="c9">Influenxing</span><span class="c1">&nbsp;is a Indian company. If you are located outside the India and choose to provide information to us, Influenxing transfers Personal Information to the India for processing, and our service providers may process Personal Information in the India and elsewhere. These countries may not have the same data protection laws as the country in which you initially provided the information. When we transfer your information to the India, we will protect it as described in this Privacy Policy.</span></p>
<p class="c4"><span class="c1">When we transfer Personal Information from territories in the EEA or with similar laws to our affiliates or service providers in the India and elsewhere outside the EEA, we rely on approved data transfer mechanisms, which may include standard contractual clauses approved by the European Commission and the Privacy Shield, as described below. You may request a copy of the standard contractual clauses relevant to your Personal Information, if any, using the contact information below.</span></p>
<h3 class="c11" id="h.azpjy2j4xcmn"><span class="c16 c10">9. PRIVACY SHIELD NOTICE</span></h3>
<p class="c4"><span class="c1">In light of the judgment of the Court of Justice of the EU in Case C-311/18, Influenxing does not rely on the Privacy Shield as a legal basis for the transfer of personal data, however, when Influenxing or one of its affiliates receives Personal Information under the Privacy Shield and then transfers it to a third party service provider acting as an agent on their behalf, Influenxing or its affiliate may have certain responsibility under the Privacy Shield if both (i) the agent processes the information in a manner inconsistent with the Privacy Shield and (ii) Influenxing or its affiliate is responsible for the event giving rise to the damage.</span></p>
<p class="c4"><span class="c1">Covered European residents should contact Influenxing at the contact information below regarding Influenxing&rsquo;s or its affiliates&#39; compliance with the Privacy Shield. Influenxing will attempt to answer your questions and satisfy your concerns in a timely and complete manner as soon as possible. If, after discussing the matter with Influenxing, your issue or complaint is not resolved, Influenxing and the above-named affiliates have agreed to participate in the Privacy Shield independent dispute resolution mechanisms listed below, free of charge to you. PLEASE CONTACT Influenxing FIRST.</span></p>
<p class="c4"><span class="c9">For other Personal Information Influenxing or its affiliates receive under the Privacy Shield, Influenxing and its affiliates have committed to refer unresolved privacy complaints under the EU-Indian and Swiss-Indian Privacy Shield Principles to an independent dispute resolution mechanism, JAMS Privacy Shield Dispute Resolution, operated by JAMS. If you do not receive timely acknowledgment of your complaint, or if your complaint is not satisfactorily addressed, please visit </span><span class="c28"><a class="c8" href="https://www.google.com/url?q=https://www.jamsadr.com/eu-us-privacy-shield&amp;sa=D&amp;source=editors&amp;ust=1677516755935699&amp;usg=AOvVaw2HerRNoFFgHrUtKopjBTF2">https://www.jamsadr.com/eu-us-privacy-shield</a></span><span class="c6">&nbsp;</span><span class="c1">for more information and to file a complaint.</span></p>
<p class="c4"><span class="c9">If your complaint still is not resolved through these channels, under limited circumstances, an additional binding arbitration option may be available before a Privacy Shield panel, as described at </span><span class="c28"><a class="c8" href="https://www.google.com/url?q=https://www.privacyshield.gov/&amp;sa=D&amp;source=editors&amp;ust=1677516755936129&amp;usg=AOvVaw09Ui896GOhBw1kmwF5WuNT">https://www.privacyshield.gov</a></span><span class="c1">. Every individual also has a right to lodge a complaint with the relevant supervisory authority.</span></p>
<h3 class="c11" id="h.7ac9r2kfwmjs"><span class="c16 c10">10. LINKS TO OTHER SITES</span></h3>
<p class="c4"><span class="c1">Our Service contains links to other websites. If you choose to click on a third party link, you will be directed to that third party&rsquo;s website. The fact that we link to a website is not an endorsement, authorization or representation of our affiliation with that third party, nor is it an endorsement of their privacy or information security policies or practices. We do not exercise control over third party websites. These other websites may place their own cookies or other files on your computer, collect data or solicit Personal Information from you. We encourage you to read the privacy policies or statements of the other websites you visit.</span></p>
<h3 class="c11" id="h.ftpbaxmf5g09"><span class="c16 c10">11. PUBLIC PROFILE</span></h3>
<p class="c4"><span class="c1">The profile you create on our Site will be publicly accessible unless otherwise indicated. This means it will be visible to the entire Internet, including clients, Influencers, visitors, and search engines such as Google and Bing, and may appear on Influenxing partners&#39; sites. You may change the privacy settings of your profile through your account portal.</span></p>
<h3 class="c11" id="h.7s2atjtcd2rl"><span class="c16 c10">12. PHISHING</span></h3>
<p class="c4"><span class="c9">Phishing websites imitate legitimate websites in order to obtain personal or financial information. Identity theft and the practice currently known as &ldquo;phishing&rdquo; are of great concern to Influenxing. For more information about phishing, visit the website of the Federal Trade Commission at </span><span class="c28"><a class="c8" href="https://www.google.com/url?q=http://www.consumer.ftc.gov/articles/0003-phishing&amp;sa=D&amp;source=editors&amp;ust=1677516755937036&amp;usg=AOvVaw3v2_0MGn-V17JATXzum7LV">http://www.consumer.ftc.gov/articles/0003-phishing</a></span><span class="c6">&nbsp;</span><span class="c9">. In addition, if you believe you have received an email or had a similar interaction with a third party pretending to be Influenxing, please report it at </span><span class="c28"><a class="c8" href="https://www.google.com/url?q=https://support.influenxing.com/&amp;sa=D&amp;source=editors&amp;ust=1677516755937319&amp;usg=AOvVaw08t76WbhywmjRX3WhJwdnB">https://support.Influenxing.com</a></span><span class="c6">&nbsp;</span><span class="c1">.</span></p>
<h3 class="c11" id="h.9m493628l8d1"><span class="c16 c10">13. CALIFORNIA AND NEVADA RESIDENTS &ndash; YOUR PRIVACY RIGHTS</span></h3>
<p class="c4"><span class="c2">NOTICE FOR CALIFORNIA RESIDENTS</span></p>
<p class="c4"><span class="c2">Please see the Supplemental Notice for California Residents below for additional details on rights available to California residents, and how to exercise such rights.</span></p>
<p class="c4"><span class="c2">NOTICE FOR NEVADA RESIDENTS</span></p>
<p class="c4"><span class="c2">Under Nevada law, certain Nevada residents may opt out of the sale of &ldquo;personally identifiable information&rdquo; for monetary consideration to a person for that person to license or sell such information to additional persons. &ldquo;Personally identifiable information&rdquo; includes first and last name, address, email address, phone number, Social Security Number, or an identifier that allows a specific person to be contacted either physically or online.</span></p>
<p class="c4"><span class="c2">We do not engage in such activity; however, if you are a Nevada resident who has purchased or leased goods or services from us, you may submit a request to opt out of any potential future sales under Nevada law by emailing privacyrequests@Influenxing.com. Please note we will take reasonable steps to verify your identity and the authenticity of the request. Once verified, we will maintain your request in the event our practices change.</span></p>
<h3 class="c11" id="h.88asoyoftoqo"><span class="c10 c16">14. CHANGES TO THIS POLICY</span></h3>
<p class="c4"><span class="c22 c9">We may change this Privacy Policy. If we make substantial changes, we will provide notice.</span></p>
<p class="c4"><span class="c9">Influenxing</span><span class="c1">&nbsp;may update this Privacy Policy at any time and any changes will be effective upon posting. In the event that there are substantial changes to the way we treat your Personal Information, we will display a notice through the Services prior to the change becoming effective. We may also notify you by email, in our discretion. However, we will use your Personal Information in a manner consistent with the Privacy Policy in effect at the time you submitted the information, unless you consent to the new or revised policy.</span></p>
<h3 class="c11" id="h.py95zwby81vh"><span class="c16 c10">15. CONTACTING US</span></h3>
<p class="c4"><span class="c1">If you have any questions about this Privacy Policy, please contact us at our helpline numbers or A-1 ground floor plot 260C Syed wadi Dr Babasaheb Jayekar marg</span></p>
<p class="c4"><span class="c1">Mumbai 400002</span></p>
<p class="c4"><span class="c25 c10 c48">16. SUPPLEMENTAL PRIVACY NOTICE FOR CALIFORNIA RESIDENTS</span></p>
<p class="c4"><span class="c2">This Supplemental Privacy Notice for California Residents supplements the information in our Privacy Policy above, and except as provided herein, applies solely to California residents. It applies to personal information we collect on or through the Service and through other means (such as information collected offline, in person, and over the telephone). It does not apply to personal information we collect from our employees or job applicants in their capacity as employees and job applicants. It also does not apply to information we collect about businesses that use our Service -- including any employees, owners, directors, officers, or contractors of those businesses -- in the course of our provision or receipt of business-related services.</span></p>
<p class="c4"><span class="c25 c24 c10">Summary of Information We Collect</span></p>
<p class="c4"><span class="c2">California law requires us to disclose information regarding the categories of personal information that we have collected about California consumers (as that term is defined in the California Consumer Privacy Act (&quot;CCPA&quot;)), the categories of sources from which the information was collected, the business or commercial purposes (as those terms are defined by applicable law) for which the information was collected, and the categories of parties with whom we share personal information.</span></p>
<p class="c4"><span class="c2">We or our service providers may collect the below categories of information for the following business or commercial purposes (as those terms are defined in applicable law):</span></p>
<ul class="c19 lst-kix_51y3x2gweqlh-0 start">
   <li class="c13 c15 li-bullet-0"><span class="c2">Providing the Service (e.g., account servicing and maintenance, matching Influencer talent with client needs, customer service, advertising and marketing, analytics, and communication about the Service);</span></li>
   <li class="c13 c15 li-bullet-0"><span class="c2">Our or our service providers&#39; operational purposes;</span></li>
   <li class="c13 c15 li-bullet-0"><span class="c2">Auditing consumer interactions on our site (e.g., measuring ad impressions);</span></li>
   <li class="c13 c15 li-bullet-0"><span class="c2">Detecting, protecting against, and prosecuting privacy and security incidents and fraudulent or illegal activity;</span></li>
   <li class="c13 c15 li-bullet-0"><span class="c2">Bug detection, error reporting, and activities to maintain the quality or safety of our Service;</span></li>
   <li class="c13 c15 li-bullet-0"><span class="c2">Investigating compliance with, enforcing, and/or complying with the law;</span></li>
   <li class="c13 c15 li-bullet-0"><span class="c2">Short-term, transient use, such as customizing content that we or our service providers display on the Service;</span></li>
   <li class="c13 c15 li-bullet-0"><span class="c2">Improving our existing Service and developing new services (e.g., by conducting research to develop new products or features);</span></li>
   <li class="c13 c15 li-bullet-0"><span class="c2">Other uses that advance our commercial or economic interests, such as third party advertising and communicating with you about relevant offers from us or third party partners;</span></li>
   <li class="c13 c15 li-bullet-0"><span class="c2">Other uses about which we notify you.</span></li>
</ul>
<p class="c4"><span class="c2">Examples of these types of uses are identified below. We may also use the below categories of personal information for compliance with applicable laws and regulations, and we may combine the information we collect (&ldquo;aggregate&rdquo;) or remove pieces of information (&ldquo;de-identify&rdquo;) to limit or prevent identification of any particular user or device.</span></p>
<a id="t.8bb4f1f86ffdef14bfbe3ec43ff0cd6b40d00298"></a><a id="t.0"></a>
<table class="c44">
   <tr class="c33">
      <td class="c14 c23" colspan="1" rowspan="1">
         <p class="c13"><span class="c5">Categories of Personal Information We Collect</span></p>
      </td>
      <td class="c30 c23" colspan="1" rowspan="1">
         <p class="c13"><span class="c5">Categories of Sources</span></p>
      </td>
      <td class="c14 c23" colspan="1" rowspan="1">
         <p class="c13"><span class="c5">Examples of Uses</span></p>
      </td>
      <td class="c14 c23" colspan="1" rowspan="1">
         <p class="c13"><span class="c5">Categories of Third Parties With Which We May Share That Information</span></p>
      </td>
   </tr>
   <tr class="c41">
      <td class="c14" colspan="1" rowspan="1">
         <p class="c13"><span class="c0">Identifiers (such as account information, name, email address, address, phone number, social network account and profile data, biometric identifiers or information such as a facial photograph, selfie, government-issued identification, or Service interaction data)</span></p>
      </td>
      <td class="c30" colspan="1" rowspan="1">
         <p class="c13"><span class="c0">You</span></p>
         <p class="c13"><span class="c0">Your use of the Service/automatically collected from you</span></p>
         <p class="c13"><span class="c0">Affiliates</span></p>
         <p class="c13"><span class="c0">Third Parties (such as agents/service providers and other users)</span></p>
      </td>
      <td class="c14" colspan="1" rowspan="1">
         <p class="c13"><span class="c0">Providing the Service, including to process your transactions, address your inquiries, provide assistance to you in using the Service, and in connection with Influenxing&rsquo;s Enterprise Compliance and other premium offerings</span></p>
         <p class="c13"><span class="c0">Fixing and improving the Service</span></p>
         <p class="c13"><span class="c0">Personalizing content</span></p>
         <p class="c13"><span class="c0">Marketing and advertising</span></p>
         <p class="c13"><span class="c0">Administering promotional activities</span></p>
         <p class="c13"><span class="c0">Communicating with you</span></p>
         <p class="c13"><span class="c0">Preventing, detecting, investigating, and responding to possible fraud, unauthorized access/use of the Service, breaches of terms and policies</span></p>
         <p class="c13"><span class="c0">Legal and investigative purposes, such as responding to lawful subpoenas or other requests for information, in order to investigate compliance with, enforce and/or comply with the law</span></p>
      </td>
      <td class="c14" colspan="1" rowspan="1">
         <p class="c13"><span class="c0">Third parties, such as service providers, Clients (e.g. where a Influencer makes his/her information available to a Client),Agencies, Influenxing Payroll vendors, and government agencies</span></p>
         <p class="c13"><span class="c0">Affiliates</span></p>
      </td>
   </tr>
   <tr class="c35">
      <td class="c14" colspan="1" rowspan="1">
         <p class="c13"><span class="c0">Commercial information (such as transaction data)</span></p>
      </td>
      <td class="c30" colspan="1" rowspan="1">
         <p class="c13"><span class="c0">You</span></p>
         <p class="c13"><span class="c0">Your use of the Service/automatically collected from you</span></p>
         <p class="c13"><span class="c0">Affiliates</span></p>
         <p class="c13"><span class="c0">Third Parties (such as agents/service providers and other users)</span></p>
      </td>
      <td class="c14" colspan="1" rowspan="1">
         <p class="c13"><span class="c0">Providing the Service, including to process your transactions, address your inquiries, provide assistance to you in using the Service, and in connection with Influenxing&rsquo;s Enterprise Compliance and other premium offerings</span></p>
         <p class="c13"><span class="c0">Fixing and improving the Service</span></p>
         <p class="c13"><span class="c0">Personalizing content</span></p>
         <p class="c13"><span class="c0">Marketing and advertising</span></p>
         <p class="c13"><span class="c0">Communicating with you</span></p>
         <p class="c13"><span class="c0">Preventing, detecting, investigating, and responding to possible fraud, unauthorized access/use of the Service, breaches of terms and policies</span></p>
         <p class="c13"><span class="c0">Legal and investigative purposes, such as responding to lawful subpoenas or other requests for information, in order to investigate compliance with, enforce and/or comply with the law</span></p>
      </td>
      <td class="c14" colspan="1" rowspan="1">
         <p class="c13"><span class="c0">Third parties, such as service providers, Clients (e.g. where a Influencer makes his/her information available to a Client), Agencies, Influenxing Payroll vendors, and government agencies</span></p>
         <p class="c13"><span class="c0">Affiliates</span></p>
      </td>
   </tr>
   <tr class="c50">
      <td class="c14" colspan="1" rowspan="1">
         <p class="c13"><span class="c0">Financial data (such as payment information)</span></p>
      </td>
      <td class="c30" colspan="1" rowspan="1">
         <p class="c13"><span class="c0">You</span></p>
         <p class="c13"><span class="c0">Your use of the Service/automatically collected from you</span></p>
         <p class="c13"><span class="c0">Affiliates</span></p>
         <p class="c13"><span class="c0">Third Parties (such as agents/service providers)</span></p>
      </td>
      <td class="c14" colspan="1" rowspan="1">
         <p class="c13"><span class="c0">Providing the Service, including to process your transactions, address your inquiries, provide assistance to you in using the Service, and in connection with Influenxing&rsquo;s Enterprise Compliance and other premium offerings</span></p>
         <p class="c13"><span class="c0">Fixing and improving the Service</span></p>
         <p class="c13"><span class="c0">Communicating with you</span></p>
         <p class="c13"><span class="c0">Preventing, detecting, investigating, and responding to possible fraud, unauthorized access/use of the Service, breaches of terms and policies</span></p>
         <p class="c13"><span class="c0">Legal and investigative purposes, such as responding to lawful subpoenas or other requests for information, in order to investigate compliance with, enforce and/or comply with the law</span></p>
      </td>
      <td class="c14" colspan="1" rowspan="1">
         <p class="c13"><span class="c0">Third parties, such as service providers, Clients (e.g. where a Influencer makes his/her information available to a Client), Agencies, Influenxing Payroll vendors, and government agencies</span></p>
         <p class="c13"><span class="c0">Affiliates</span></p>
      </td>
   </tr>
   <tr class="c34">
      <td class="c14" colspan="1" rowspan="1">
         <p class="c13"><span class="c0">Internet or other network or device activity (such as IP address, unique device and app identifiers, browsing history or other usage data)</span></p>
      </td>
      <td class="c30" colspan="1" rowspan="1">
         <p class="c13"><span class="c0">You</span></p>
         <p class="c13"><span class="c0">Your use of the Service/automatically collected from you</span></p>
         <p class="c13"><span class="c0">Affiliates</span></p>
         <p class="c13"><span class="c0">Third Parties (such as agents/service providers)</span></p>
      </td>
      <td class="c14" colspan="1" rowspan="1">
         <p class="c13"><span class="c0">Providing the Service, including to process your transactions, address your inquiries, provide assistance to you in using the Service, and in connection with Influenxing&rsquo;s Enterprise Compliance and other premium offerings</span></p>
         <p class="c13"><span class="c0">Fixing and improving the Service</span></p>
         <p class="c13"><span class="c0">Personalizing content</span></p>
         <p class="c13"><span class="c0">Marketing and advertising</span></p>
         <p class="c13"><span class="c0">Preventing, detecting, investigating, and responding to possible fraud, unauthorized access/use of the Service, breaches of terms and policies</span></p>
         <p class="c13"><span class="c0">Legal and investigative purposes, such as responding to lawful subpoenas or other requests for information, in order to investigate compliance with, enforce and/or comply with the law</span></p>
      </td>
      <td class="c14" colspan="1" rowspan="1">
         <p class="c13"><span class="c0">Third parties, such as service providers, Clients (e.g. where a Influencer makes his/her information available to a Client), Agencies, Influenxing Payroll vendors, and government agencies</span></p>
         <p class="c13"><span class="c0">Affiliates</span></p>
      </td>
   </tr>
   <tr class="c34">
      <td class="c14" colspan="1" rowspan="1">
         <p class="c13"><span class="c0">General Location information</span></p>
      </td>
      <td class="c30" colspan="1" rowspan="1">
         <p class="c13"><span class="c0">You</span></p>
         <p class="c13"><span class="c0">Your use of the Service/automatically collected from you</span></p>
         <p class="c13"><span class="c0">Affiliates</span></p>
         <p class="c13"><span class="c0">Third Parties (such as agents/service providers)</span></p>
      </td>
      <td class="c14" colspan="1" rowspan="1">
         <p class="c13"><span class="c0">Providing the Service, including to process your transactions, address your inquiries, provide assistance to you in using the Service, and in connection with Influenxing&rsquo;s Enterprise Compliance and other premium offerings</span></p>
         <p class="c13"><span class="c0">Fixing and improving the Service</span></p>
         <p class="c13"><span class="c0">Personalizing content</span></p>
         <p class="c13"><span class="c0">Marketing and advertising</span></p>
         <p class="c13"><span class="c0">Preventing, detecting, investigating, and responding to possible fraud, unauthorized access/use of the Service, breaches of terms and policies</span></p>
         <p class="c13"><span class="c0">Legal and investigative purposes, such as responding to lawful subpoenas or other requests for information, in order to investigate compliance with, enforce and/or comply with the law</span></p>
      </td>
      <td class="c14" colspan="1" rowspan="1">
         <p class="c13"><span class="c0">Third parties, such as service providers, Clients (e.g. where a Influencer makes his/her information available to a Client), Agencies, Influenxing Payroll vendors, and government agencies</span></p>
         <p class="c13"><span class="c0">Affiliates</span></p>
      </td>
   </tr>
   <tr class="c39">
      <td class="c14" colspan="1" rowspan="1">
         <p class="c13"><span class="c0">Sensory information (such as audio recordings if you call our customer service, video recording (if you provide permission), or screenshots from Work Diaries)</span></p>
      </td>
      <td class="c30" colspan="1" rowspan="1">
         <p class="c13"><span class="c0">You</span></p>
         <p class="c13"><span class="c0">Your use of the Service/automatically collected from you</span></p>
         <p class="c13"><span class="c0">Affiliates</span></p>
         <p class="c13"><span class="c0">Third Parties (such as agents/service providers)</span></p>
      </td>
      <td class="c14" colspan="1" rowspan="1">
         <p class="c13"><span class="c0">Providing the Service, including to process your transactions, address your inquiries, provide assistance to you in using the Service, and in connection with Influenxing&rsquo;s Enterprise Compliance and other premium offerings</span></p>
         <p class="c13"><span class="c0">Fixing and improving the Service</span></p>
         <p class="c13"><span class="c0">Preventing, detecting, investigating, and responding to possible fraud, unauthorized access/use of the Service, breaches of terms and policies</span></p>
         <p class="c13"><span class="c0">Legal and investigative purposes, such as responding to lawful subpoenas or other requests for information, in order to investigate compliance with, enforce and/or comply with the law</span></p>
      </td>
      <td class="c14" colspan="1" rowspan="1">
         <p class="c13"><span class="c0">Third parties, such as service providers, Clients (e.g. where a Influencer makes his/her information available to a Client), Agencies, Influenxing Payroll vendors, and government agencies</span></p>
         <p class="c13"><span class="c0">Affiliates</span></p>
      </td>
   </tr>
   <tr class="c41">
      <td class="c14" colspan="1" rowspan="1">
         <p class="c13"><span class="c0">Other information that identifies or can be reasonably associated with you (such as user generated content, e.g. community posts, feedback and job postings, in each case, when the content can be used to identify you)</span></p>
      </td>
      <td class="c30" colspan="1" rowspan="1">
         <p class="c13"><span class="c0">You</span></p>
         <p class="c13"><span class="c0">Your use of the Service/automatically collected from you</span></p>
         <p class="c13"><span class="c0">Affiliates</span></p>
         <p class="c13"><span class="c0">Third Parties (such as agents/service providers)</span></p>
      </td>
      <td class="c14" colspan="1" rowspan="1">
         <p class="c13"><span class="c0">Providing the Service, including to process your transactions, address your inquiries, provide assistance to you in using the Service, and in connection with Influenxing&rsquo;s Enterprise Compliance and other premium offerings</span></p>
         <p class="c13"><span class="c0">Fixing and improving the Service</span></p>
         <p class="c13"><span class="c0">Personalizing content</span></p>
         <p class="c13"><span class="c0">Marketing and advertising</span></p>
         <p class="c13"><span class="c0">Administer promotional activities</span></p>
         <p class="c13"><span class="c0">Communicating with you</span></p>
         <p class="c13"><span class="c0">Preventing, detecting, investigating, and responding to possible fraud, unauthorized access/use of the Service, breaches of terms and policies</span></p>
         <p class="c13"><span class="c0">Legal and investigative purposes, such as responding to lawful subpoenas or other requests for information, in order to investigate compliance with, enforce and/or comply with the law</span></p>
      </td>
      <td class="c14" colspan="1" rowspan="1">
         <p class="c13"><span class="c0">Third parties, such as service providers, Clients (e.g. where a Influencer makes his/her information available to a Client), Agencies, Influenxing Payroll vendors, and government agencies</span></p>
         <p class="c13"><span class="c0">Affiliates</span></p>
         <p class="c13"><span class="c0">The public if you or other users post content publicly</span></p>
      </td>
   </tr>
</table>
<p class="c4"><span class="c25 c24 c10">Rights</span></p>
<p class="c4"><span class="c2">If you are a California resident, you may have certain rights. California law may permit you to request that we:</span></p>
<ul class="c19 lst-kix_urr50sllmjv0-0 start">
   <li class="c13 c15 li-bullet-0"><span class="c2">Provide you the categories of personal information we have collected or disclosed about you in the last twelve months; the categories of sources of such information; the business or commercial purpose for collecting or selling your personal information; and the categories of third parties with whom we shared personal information.</span></li>
   <li class="c13 c15 li-bullet-0"><span class="c2">Provide access to and/or a copy of certain information we hold about you.</span></li>
   <li class="c13 c15 li-bullet-0"><span class="c2">Delete certain information we have about you.</span></li>
</ul>
<p class="c4"><span class="c2">You may have the right to receive information about the financial incentives that we offer to you, if any. You also have the right to not be discriminated against (as provided for in applicable law) for exercising certain of your rights.</span></p>
<p class="c4"><span class="c24">If you would like to exercise any of these rights, please submit a request through the Data Request Form available in our </span><span class="c31 c46"><a class="c8" href="https://www.google.com/url?q=https://influenxing.com/s/f89b37df-42d9-4971-bbcc-466469a68600/legal.html%23gdpr&amp;sa=D&amp;source=editors&amp;ust=1677516755960549&amp;usg=AOvVaw0S9ddQQ5u7gUuo2PqrZ69Y">Privacy Center</a></span><span class="c2">&nbsp;or email us at influenxing.tech@gmail.com. You will be required to verify your identity before we fulfill your request. You can also designate an authorized agent to make a request on your behalf. To do so, you must provide us with written authorization or a power of attorney, signed by you, for the agent to act on your behalf. You will still need to verify your identity directly with us.</span></p>
<p class="c4"><span class="c2">Certain information may be exempt from such requests under applicable law. For example, we need certain types of information so that we can provide the Service to you. If you ask us to delete it, you may no longer be able to access or use the Service.</span></p>
<p class="c4"><span class="c2">The CCPA sets forth certain obligations for businesses that &ldquo;sell&rdquo; personal information. Based on the definition of &ldquo;sell&rdquo; under the CCPA and under current regulatory guidance, we do not believe we engage in such activity and have not engaged in such activity in the past twelve months.</span></p>
<p class="c4"><span class="c31 c24 c10 c47">Accessibility</span></p>
<p class="c4"><span class="c0">This Privacy Policy uses industry-standard technologies and was developed in connection with the World Wide Web Consortium&#39;s Web Content Accessibility Guidelines, version 2.1. If you wish to print this policy, please do so from your web browser or by saving the page as a PDF.</span></p>
<p class="c21"><span class="c25 c38 c45"></span></p>
      </div>`;

var PrivacyPolicy = function () {
  var PrivacyPolicy = {
    text: Privacy,
  };
  return PrivacyPolicy;
};
